export const TOURS = [
  { id:'half-day-ubud', name:'Half Day Ubud Discovery', category:'Half Day Tour', duration:'5 hours', basePrice:55, description:'Explore Tegalalang rice terraces, Tirta Empul temple, and Ubud Palace in a relaxed half-day.', highlights:['Tegalalang Rice Terraces','Tirta Empul Temple','Ubud Palace'], includes:['Air-conditioned vehicle','English guide','Entry fees','Water'], image:'https://images.unsplash.com/photo-1537996194471-e657df975ab4?w=800&q=80&fit=crop' },
  { id:'half-day-tanah-lot', name:'Half Day Tanah Lot Sunset', category:'Half Day Tour', duration:'4 hours', basePrice:55, description:'Watch the sun set behind Tanah Lot sea temple.', highlights:['Tanah Lot Temple','Sunset view','Pura Taman Ayun'], includes:['Air-conditioned vehicle','English guide','Entry fees','Water'], image:'https://images.unsplash.com/photo-1604999333679-b86d54738315?w=800&q=80&fit=crop' },
  { id:'full-day-east-bali', name:'Full Day East Bali Explorer', category:'Full Day Tour', duration:'10 hours', basePrice:89, description:'Tirta Gangga, Lempuyang Temple, and Besakih.', highlights:['Tirta Gangga','Lempuyang Gate of Heaven','Pura Besakih'], includes:['Vehicle','Guide','Entry fees','Lunch','Water'], image:'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=800&q=80&fit=crop' },
  { id:'full-day-north-bali', name:'Full Day North Bali & Kintamani', category:'Full Day Tour', duration:'10 hours', basePrice:89, description:'Sekumpul waterfall, Lake Batur, Bedugul, and Ulun Danu temple.', highlights:['Sekumpul Waterfall','Kintamani View','Bedugul & Ulun Danu'], includes:['Vehicle','Guide','Entry fees','Lunch','Water'], image:'https://images.unsplash.com/photo-1527090526205-befd3e1fa299?w=800&q=80&fit=crop' },
  { id:'all-inclusive', name:'All-Inclusive Bali Highlights', category:'All Inclusive', duration:'12 hours', basePrice:145, description:'Temples, rice terraces, waterfalls, and cultural performances — all included.', highlights:['Tegalalang','Tirta Empul','Uluwatu Kecak Dance','Jimbaran Dinner'], includes:['Premium vehicle','Expert guide','All entry fees','Lunch & dinner','Hotel pickup'], image:'https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=800&q=80&fit=crop' },
  { id:'nusa-penida', name:'Nusa Penida Island Day Tour', category:'Nusa Penida', duration:'11 hours', basePrice:95, description:'Kelingking viewpoint, Broken Beach, Angel Billabong, and crystal-clear snorkelling.', highlights:['Kelingking Beach','Broken Beach','Crystal Bay Snorkelling'], includes:['Fast boat return','Jeep & guide','Entry fees','Lunch','Snorkel gear'], image:'https://images.unsplash.com/photo-1555400038-63f5ba517a47?w=800&q=80&fit=crop' },
  { id:'adventure', name:'White Water Rafting Adventure', category:'Adventure', duration:'4 hours', basePrice:75, description:'Grade II-III rapids on the Ayung or Telaga Waja river through jungle gorges.', highlights:['Grade II-III rapids','Jungle canyon','Waterfall shower'], includes:['Safety equipment','Guide','Shower room','Lunch buffet'], image:'https://images.unsplash.com/photo-1571997799836-4fdd95c4b2c3?w=800&q=80&fit=crop' }
];

export function getTourById(id) {
  return TOURS.find(t => t.id === id) || TOURS[0];
}
